sudo: required
env:
  matrix:
  - TEST_SUITE=unit-test
services:
- docker
language: go
go:
- '1.11.4'
go_import_path: openpitrix.io/notification
script:
- make fmt-check
- make check
- env GO111MODULE=on make $TEST_SUITE
deploy:
- provider: script
  script: bash docker_push latest
  on:
    branch: master
    repo: openpitrix/notification
- provider: script
  script: bash docker_push $TRAVIS_TAG
  on:
    tags: true
    repo: openpitrix/notification
