sudo: required
services:
- docker
language: go
go:
- '1.11'
go_import_path: openpitrix.io/notification
script:
- make fmt-check
- make check
deploy:
- provider: script
  script: bash docker_push latest
  on:
    branch: master
    repo: openpitrix/notification
- provider: script
  script: bash docker_push $TRAVIS_TAG
  on:
    tags: true
    repo: openpitrix/notification
