# Copyright 2018 The OpenPitrix Authors. All rights reserved.
# Use of this source code is governed by a Apache license
# that can be found in the LICENSE file.

version: '3'

services:
  # notification mysql db
  notification-db:
    image: "mysql:8.0.11"
    environment:
    - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    volumes:
    - ${DATA_PATH}/mysql:/var/lib/mysql
    - ./pkg/db/ddl:/docker-entrypoint-initdb.d
    command: --lower_case_table_names=0
    ports:
    - "13306:3306" # for unit-test & debug
    container_name: "notification-db"
    logging:
      driver: "json-file"
      options:
        max-size: ${NOTIFICATION_LOG_MAX_SIZE}
        max-file: ${NOTIFICATION_LOG_MAX_FILE}

  # notification etcd
  notification-etcd:
    image: "quay.io/coreos/etcd:v3.2.18"
    command: etcd --data-dir /data --listen-client-urls http://0.0.0.0:2379 --advertise-client-urls http://notification-etcd:2379 --max-snapshots 5 --max-wals 5 --auto-compaction-retention=168
    volumes:
    - ${DATA_PATH}/etcd:/data
    ports:
    - "12379:2379" # for unit-test & debug
    container_name: "notification-etcd"
    logging:
      driver: "json-file"
      options:
        max-size: ${NOTIFICATION_LOG_MAX_SIZE}
        max-file: ${NOTIFICATION_LOG_MAX_FILE}

  # notification service
  notification-manager:
    #build: .
    #image: "notification_server:v0.0.1-dev"
    image: "notification:v0.0.1-dev"
    command: "notification-manager"
    links:
    - notification-db:notification-db
    - notification-etcd:notification-etcd
    depends_on:
    - notification-notification-db-ctrl
    - notification-etcd
    container_name: "notification-manager"
    environment:
    - NOTIFICATION_LOG_LEVEL=${NOTIFICATION_LOG_LEVEL}
    - NOTIFICATION_GRPC_SHOW_ERROR_CAUSE=${NOTIFICATION_GRPC_SHOW_ERROR_CAUSE}
    - NOTIFICATION_MYSQL_DATABASE=notification
    logging:
      driver: "json-file"
      options:
        max-size: ${NOTIFICATION_LOG_MAX_SIZE}
        max-file: ${NOTIFICATION_LOG_MAX_FILE}
    #ports:
    #- "9201:9201"
  notification-notification-db-ctrl:
    image: dhoer/flyway:5.1.4-mysql-8.0.11-alpine
    command: -url=jdbc:mysql://notification-db/notification -user=root -password=${MYSQL_ROOT_PASSWORD} -validateOnMigrate=false migrate
    volumes:
    - ./pkg/db/schema/notification:/flyway/sql
    links:
    - notification-db:notification-db
    depends_on:
    - notification-db
    container_name: "notification-notification-db-ctrl"
